name: Build and Publish to NPM

on: [workflow_dispatch]

defaults:
  run:
    working-directory: packages/storybook-builder-vite

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: npm / registry setup ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/

    - name: install, build, and test
      run: |
        yarn install
        yarn workspaces foreach -p run build-storybook
      env:
        CI: true

    - name: Publish if version is new
      continue-on-error: true
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
